# Generated by Django 4.0.5 on 2023-03-01 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_state_alter_locations_options_terminal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminal',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='locations.state'),
        ),
    ]
