# Generated by Django 4.1.7 on 2023-03-02 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_alter_state_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ('name',)},
        ),
    ]
