# Generated by Django 4.1.7 on 2023-03-02 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_alter_state_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Locations',
        ),
    ]
