# Generated by Django 4.0.5 on 2023-03-02 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_delete_locations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
                ('departure', models.CharField(max_length=200)),
                ('arrival', models.CharField(max_length=200)),
                ('date_of_trip', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
