# Generated by Django 4.0.5 on 2023-03-02 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0008_trips'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trips',
            old_name='image',
            new_name='image_url',
        ),
    ]
