# Generated by Django 4.0.5 on 2023-03-02 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0009_rename_image_trips_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trips',
            name='date_of_trip',
        ),
    ]
