# Generated by Django 4.1.7 on 2023-03-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0011_trips_transport_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
